name: build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          cd core
          docker build -f Dockerfile.dev -t oqtopus-dev .

      - name: Save image
        run: |
          docker save oqtopus-dev | gzip > oqtopus-dev.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oqtopus-dev
          path: oqtopus-dev.tar.gz
