name: build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          cd combiner
          docker build -t combiner -f Dockerfile.dev .
      - name: Save image
        run: |
          docker save combiner | gzip > combiner.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: combiner
          path: combiner.tar.gz
